apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: analytics
      port: 8123
      protocol: http
      tlsSkipVerify: true
    version: 1
    editable: true

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: analytics
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true
    version: 1
    editable: true
